tosca_definitions_version: cloudify_dsl_1_3


imports:
  - https://cloudify.co/spec/cloudify/6.2.0/types.yaml
  - plugin:cloudify-terraform-plugin

inputs:
  vpc_tf_url:
    type: string
    default:
      concat:
        - https://github.com/
        - { get_input: repo_full_name }
        - "/archive/refs/heads/master.zip"

node_templates:

  terraform:
    type: cloudify.nodes.terraform
  
  vpc:
    type: cloudify.nodes.terraform.Module
    properties:
      resource_config:
        source:
          location: { get_input: vpc_tf_url }
          username: { get_secret: github_token }
          password: x-oauth-basic
        source_path: templates/aws/vpc
        variables:
          access_key: { get_secret: aws_access_key_id }
          secret_key: { get_secret: aws_secret_access_key }
          aws_region: { get_input: [resource_config, aws_region_name] }
          public_key: { get_secret: cert_key_public }
          vpc_cidr: { get_input: [resource_config, vpc_cidr] }
          subnet_cidr: { get_input: [resource_config, subnet_cidr] }
          availability_zone: { concat: [ { get_input: [resource_config, aws_region_name] }, "a" ] }
    relationships:
      - type: cloudify.terraform.relationships.run_on_host
        target: terraform